### ISSUE TITLE
[Bug] freeorion and boost 1.48.0 [sf#503]

### ISSUE THREAD

**Issue by adrianbroher** [adrianbroher/freeorion-tickets-test#136]
**Reported by alexanro on 2011-12-14 19:38 UTC**
Hello,

freeorion compiles fine with gcc 4.6.2 and the latest version of gigi on 64-bit Arch Linux.
However, after the latest upgrade of the official boost package to 1.48.0, freeorion no longer compiles.

Here is the error message for the latest version of freeorion \(svn revision 4517\):

\[...\]
\[ 53%\] Building CXX object CMakeFiles/parse\_static.dir/parse/ShipPartsParser.cpp.o
In file included from /usr/include/boost/spirit/home/phoenix/core.hpp:13:0,
from /usr/include/boost/spirit/include/phoenix\_core.hpp:14,
from /usr/include/boost/spirit/home/support/terminal.hpp:16,
from /usr/include/boost/spirit/home/support/common\_terminals.hpp:15,
from /usr/include/boost/spirit/home/lex/lexer/terminals.hpp:13,
from /usr/include/boost/spirit/home/lex/lexer.hpp:13,
from /usr/include/boost/spirit/home/lex.hpp:13,
from /usr/include/boost/spirit/home/lex/lexer\_lexertl.hpp:15,
from /usr/include/boost/spirit/include/lex\_lexertl.hpp:16,
from /usr/include/GG/LexerFwd.h:34,
from /home/alexander/archpackages/freeorion/src/freeorion-build/parse/Lexer.h:7,
from /home/alexander/archpackages/freeorion/src/freeorion-build/parse/Double.h:5,
from /home/alexander/archpackages/freeorion/src/freeorion-build/parse/ShipPartsParser.cpp:3:
/usr/include/boost/spirit/home/phoenix/core/actor.hpp:15:3: error: \#error "BOOST\_RESULT\_OF\_NUM\_ARGS &lt; PHOENIX\_ACTOR\_LIMIT"
make\[2\]: \*\*\* \[CMakeFiles/parse\_static.dir/parse/ShipPartsParser.cpp.o\] Error 1
make\[1\]: \*\*\* \[CMakeFiles/parse\_static.dir/all\] Error 2
make: \*\*\* \[all\] Error 2

Please make freeorion compile with boost 1.48.0.
